stages:
  - build

llm-dev:
  stage: build
  tags:
    - gcp
  script:
    - echo "Deploying fastapi and ollama-dev services."
    - |
      sshpass -p $XPLOR_LLM_PASSWORD ssh $Default_Username@$XPLOR_LLM_HOST "
        if [[ -d xplor-llm-summarizer ]]; then
          cd /home/ubuntu/xplor-llm-summarizer
          docker-compose down
          cd /home/ubuntu/ &&  sudo rm -rf xplor-llm-summarizer
        fi "
    - sshpass -p $XPLOR_LLM_PASSWORD ssh $Default_Username@$XPLOR_LLM_HOST  "git clone -b new_develop https://user:'$GITLAB_ACCESS_TOKEN'@gitlab.thewitslab.com/wil-workspace/xplor/xplor-llm-summarizer.git"
    - sshpass -p $XPLOR_LLM_PASSWORD ssh -tt $Default_Username@$XPLOR_LLM_HOST "
        cd /home/ubuntu/xplor-llm-summarizer && docker-compose up -d --build "
    - echo -e "
      Dev Fast-API Backend URL:- https://fastapi-backend.thewitslab.com/\n
      Dev Ollama Backend URL:- https://ollama-backend.thewitslab.com/"
  