version: '3.8'

services:
  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: ollama-dev
    ports:
      - "11434:11434"
      
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-dev
    ports:
      - 8555:8000
    command: ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000"]
